server.port=${PORT:8082}

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# ===============================
# JPA CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===============================
# MAIL CONFIG
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2codewithdivyansh@gmail.com
spring.mail.password=habneicbacrnxiat
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
portfolio.admin.email=2codewithdivyansh@gmail.com